services:
  postgres:
    container_name: inkara_postgres
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
      TZ: 'Etc/UTC'
    volumes:
      - postgres:/data/postgres
    networks:
      - ${NETWORK}

networks:
  inkara_network:
    driver: bridge
    name: ${NETWORK}

volumes:
  postgres:
