version: '3.7'

services:
  backend:
    container_name: mezas_backend
    build:
      context: .
      dockerfile: docker/Dockerfile
    # command: npm run start:dev
    env_file:
      - .env
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/mezas
      - /usr/src/mezas/node_modules
      - /usr/src/mezas/build
    depends_on:
      - postgres
    networks:
      - mezas-network

  postgres:
    container_name: mezas_postgres
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
      TZ: 'Etc/UTC'
    volumes:
      - postgres:/data/postgres
    networks:
      - mezas-network

networks:
  mezas-network:
    driver: bridge

volumes:
  postgres: