services:
  inkara_backend:
    container_name: inkara_backend
    build:
      context: .
      dockerfile: docker/Dockerfile
    # command: npm run start:dev
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ${NETWORK}

  postgres:
    container_name: inkara_postgres
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
      TZ: 'Etc/UTC'
    volumes:
      - postgres:/data/postgres
    networks:
      - ${NETWORK}

  redis:
    container_name: inkara_redis
    image: redis:latest
    ports:
      - '6379:6379'
    environment:
      TZ: 'Etc/UTC'
    volumes:
      - redis:/data
    networks:
      - ${NETWORK}

networks:
  inkara_network:
    driver: bridge
    name: ${NETWORK}

volumes:
  postgres:
  redis:
