name: Continuous Integration and Deployment

on:
  push:
    branches:
      - develop

jobs:
  lint-commit-msg:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Lint commit message
        run: echo "$CI_COMMIT_MESSAGE" | npx commitlint

  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Lint code using ESLint
        run: echo "$CI_COMMIT_MESSAGE" | npx eslint

  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup SSH and deploy to development server
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_IP_SERVER: ${{ secrets.SSH_IP_SERVER }}
          if: github.ref == 'refs/heads/develop'
        run: |
          ssh -tt -o StrictHostKeyChecking=no $SSH_USER@$SSH_IP_SERVER "cd Inkara-SocialFi-BE && git pull && docker-compose build && docker rm -f Inkara-SocialFi-BE && docker-compose up -d"
          ssh -tt -o StrictHostKeyChecking=no $SSH_USER@$SSH_IP_SERVER "yes | docker image prune --filter 'dangling=true'"
